export const TABLE_NAME = {
    PHONG_DOC: "PHONG_DOC",
    NGUOI_DUNG: "NGUOI_DUNG",
    KE_SACH: "KE_SACH",
    SACH: "SACH",
    TAC_GIA: "TAC_GIA",
    DANH_MUC_SACH: "DANH_MUC_SACH",
    REF_SACH_TACGIA: "REF_SACH_TACGIA",
    PHIEU: "PHIEU",
}